[package]
name = "rhusics-ecs"
version = "0.4.0-alpha1"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]
repository = "https://github.com/rustgd/rhusics.git"
homepage = "https://github.com/rustgd/rhusics.git"

license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rhusics-ecs"
description = "Physics library for use with `specs`"

keywords = ["gamedev", "cgmath", "specs", "physics"]

[features]
eders = ["serde", "cgmath/serde", "collision/eders", "specs/serde", "rhusics-core/eders"]

[dependencies]
cgmath = "0.16"
collision = { version = "0.16" }
rhusics-core = { version = "0.4.0-alpha1", path = "../rhusics-core", features = ["specs"] }
specs = { version = "0.11.0-alpha4" }
shred = { version = "0.7.0-alpha5" }
shred-derive = { version = "0.5.0-alpha1" }
shrev = { version = "0.8" }
serde = { version = "1.0", optional = true, features = ["derive"]}

[[example]]
name = "basic2d"

[[example]]
name = "basic3d"

[[example]]
name = "spatial3d"

[[example]]
name = "spatial2d"
