[package]
name = "rhusics-core"
version = "0.7.0"
authors = ["Simon Rönnberg <seamonr@gmail.com>"]
repository = "https://github.com/rustgd/rhusics.git"
homepage = "https://github.com/rustgd/rhusics.git"

license = "MIT OR Apache-2.0"
documentation = "https://docs.rs/rhusics-core"
description = "Physics library for use with `specs`"

keywords = ["gamedev", "cgmath", "specs", "physics"]

[dependencies]
cgmath = "*"
# collision = "*"
collision = { git = "https://github.com/rustgd/collision-rs" }
rhusics-transform = { version = "0.4.0", path = "../rhusics-transform" }
specs = { version = "0.14", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"]}

[target.'cfg(feature = "serde")'.dependencies]
cgmath = { version = "*", features = ["serde"] }
#collision = { version = "*", features = ["serde"] }
collision = { git = "https://github.com/rustgd/collision-rs", features = ["serde"] }

[dev-dependencies]
approx = "0.3"
